config/routes.rb
Rails.application.routes.draw do
  resources :ticket_loops
  resources :tickets
  root to: 'home#index'

  devise_for :users, path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    sign_up: 'register', edit: 'edit/profile'
  }

  #Authenticated user root route
  get 'welcome', to: 'welcome#index', as: :authenticated_root

  #Admin root route
  get 'admins', to: 'admins#index', as: :admin_root

  #Agent root route
  get 'agents', to: 'agents#index', as: :agent_root

  #Customer root route
  get 'customers', to: 'customers#index', as: :customer_root

  #Admin routes
  scope '/admins' do
    resources :tickets, :users, :ticket_loops
  end

  #Customer routes
  scope '/customers' do
    resources :tickets, :ticket_loops
  end

  #Agent routes
  scope '/agents' do
    resources :tickets, :ticket_loops
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :ticket_loops
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true

  enum status: [ :open, :closed ]
end

app/models/ticket_loop.rb
class TicketLoop < ApplicationRecord
  belongs_to :ticket

  validates :description, presence: true
  enum role: [ :admin, :agent, :customer ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [ :admin, :agent, :customer ]
  after_initialize :set_default_role, :if => :new_record?

  has_many :tickets

  def set_default_role
    self.role ||= :customer
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_user

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # Overwriting the sign_up redirect path method
  def after_sign_up_path_for(resource_or_scope)
    authenticated_root_path
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  # Overwriting the sign_in redirect path method
  def after_sign_in_path_for(resource_or_scope)
    authenticated_root_path
  end

  #Setting user
  def set_user
    if user_signed_in?
      @user = current_user
    else
      false
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  layout 'backend'
  def index
    @tickets = @user.tickets
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?

    end
  end
end

app/controllers/ticket_loops_controller.rb
class TicketLoopsController < ApplicationController
  before_action :set_ticket_loop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'backend'

  # GET /ticket_loops
  # GET /ticket_loops.json
  def index
    @ticket_loops = TicketLoop.all
  end

  # GET /ticket_loops/1
  # GET /ticket_loops/1.json
  def show
  end

  # GET /ticket_loops/new
  def new
    @ticket_loop = TicketLoop.new
  end

  # GET /ticket_loops/1/edit
  def edit
  end

  # POST /ticket_loops
  # POST /ticket_loops.json
  def create
    @ticket_loop = TicketLoop.new(ticket_loop_params)
    @ticket_loop.role = @user.role
    Ticket.find(@ticket_loop.ticket_id).update_attribute(:status, 'open')

    respond_to do |format|
      if @ticket_loop.save
        format.html { redirect_to :back, notice: 'Reply created successfully.' }
        format.json { render :show, status: :created, location: @ticket_loop }
      else
        format.html { render :new }
        format.json { render json: @ticket_loop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_loops/1
  # PATCH/PUT /ticket_loops/1.json
  def update
    respond_to do |format|
      if @ticket_loop.update(ticket_loop_params)
        format.html { redirect_to @ticket_loop, notice: 'Ticket loop was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_loop }
      else
        format.html { render :edit }
        format.json { render json: @ticket_loop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_loops/1
  # DELETE /ticket_loops/1.json
  def destroy
    @ticket_loop.destroy
    respond_to do |format|
      format.html { redirect_to ticket_loops_url, notice: 'Ticket loop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_loop
      @ticket_loop = TicketLoop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_loop_params
      params.require(:ticket_loop).permit(:ticket_id, :description)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'backend'

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = @user.tickets
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket_loop = TicketLoop.new
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = @user.id

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to :back, notice: 'Ticket created successfully.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to :back, notice: 'Ticket successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.role == "admin"
      redirect_to admin_root_path
    elsif current_user.role == "agent"
      redirect_to agent_root_path
    elsif current_user.role == "customer"
      redirect_to customer_root_path
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ticket_loops_helper.rb
module TicketLoopsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agents/index.html.erb
<h1>Welcome Agent : <%= @user.name %></h1>

app/views/customers/index.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      My Dashboard
    </h1>
  </div>
</div>
<!-- /.row -->

<% if notice %>
    <div class="alert alert-success">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>

<div class="row control-group">
  <a href="/customers/tickets/new" type="button" class="btn btn-success">Make a ticket</a>
</div>

<div class="row">
  <br>
  <div class="col-lg-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"> My all support tickets</h3>
      </div>
      <div class="panel-body">
        <table id="tickets" class="display" cellspacing="0" width="100%">
          <thead>
          <tr>
            <th>SL</th>
            <th>Ticket Title</th>
            <th>Ticket Description</th>
            <th>Status</th>
            <th>Created Date</th>
            <th>Edit</th>
            <th>Details</th>
          </tr>
          </thead>
          <tbody>
          <% sl = 1 %>
          <% @tickets.each do |ticket| %>
              <tr>
                <td><%= sl %></td>
                <td><%= ticket.title %></td>
                <td><%= ticket.description.truncate_words(5) %></td>
                <td><%= ticket.status %></td>
                <td><%= ticket.created_at.strftime("%m-%d-%Y") %></td>
                <td><a href="/customers/tickets/<%= ticket.id %>/edit">Edit</a></td>
                <td><a href="/customers/tickets/<%= ticket.id %>">Details</a></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<% content_for :special_script do %>
    <script>
        $(document).ready(function() {
            $('#tickets').DataTable();
        } );
    </script>
<% end %>

app/views/home/index.html.erb
<form class="well form-horizontal" id="contact_form">
  <fieldset>
    <!-- Form Name -->
    <legend><center><h2><b>Rails 5 Customer Ticketing System</b></h2></center></legend><br>
  </fieldset>
</form>

app/views/ticket_loops/_form.html.erb
<%= form_for(ticket_loop) do |f| %>
  <% if ticket_loop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket_loop.errors.count, "error") %> prohibited this ticket_loop from being saved:</h2>

      <ul>
      <% ticket_loop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_loops/edit.html.erb
<h1>Editing Ticket Loop</h1>

<%= render 'form', ticket_loop: @ticket_loop %>

<%= link_to 'Show', @ticket_loop %> |
<%= link_to 'Back', ticket_loops_path %>

app/views/ticket_loops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ticket Loops</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_loops.each do |ticket_loop| %>
      <tr>
        <td><%= link_to 'Show', ticket_loop %></td>
        <td><%= link_to 'Edit', edit_ticket_loop_path(ticket_loop) %></td>
        <td><%= link_to 'Destroy', ticket_loop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket Loop', new_ticket_loop_path %>

app/views/ticket_loops/new.html.erb
<h1>New Ticket Loop</h1>

<%= render 'form', ticket_loop: @ticket_loop %>

<%= link_to 'Back', ticket_loops_path %>

app/views/ticket_loops/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ticket_loop_path(@ticket_loop) %> |
<%= link_to 'Back', ticket_loops_path %>

app/views/tickets/_form.html.erb
<% if ticket.errors.any? %>
    <div class="alert alert-danger">
      <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </div>
<% end %>
<% if notice %>
    <div class="alert alert-success">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>
<form id="validation" role="form" action="/customers/tickets/<% if action == 'update' %><%= @ticket.id %><% end %>" method="post">
  <% if action == 'update' %>
      <input name="utf8" type="hidden" value="&#x2713;">
      <input type="hidden" name="_method" value="patch">
  <% end %>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <div class="form-group">
    <label>Ticket Title</label>
    <input class="form-control" name="ticket[title]" id="ticket_title" value="<%= @ticket.title%>">
  </div>
  <div class="form-group">
    <label>Ticket Description</label>
    <textarea class="form-control" rows="8" name="ticket[description]" id="ticket_description"><%= @ticket.description%></textarea>
  </div>
  <button type="submit" class="btn btn-default">Submit Ticket</button>
</form>

app/views/tickets/_reply.html.erb
<% if ticket_loop.errors.any? %>
    <div class="alert alert-danger">
      <% ticket_loop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </div>
<% end %>
<form id="validation" role="form" action="/customers/ticket_loops" method="post">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type="hidden" name="ticket_loop[ticket_id]" value="<%= ticket_id %>">
  <div class="form-group">
    <label>Make a reply</label>
    <textarea class="form-control" rows="3" name="ticket_loop[description]"></textarea>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

app/views/tickets/edit.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      My Dashboard
    </h1>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"> Edit ticket</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', ticket: @ticket, action: 'update' %>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<% content_for :special_script do %>
    <script>
        $(document).ready(function() {
            $("#validation").validate({
                rules: {
                    'ticket[title]': {
                        required: true
                    },
                    'ticket[description]': {
                        required: true
                    }
                },
                messages: {
                    'ticket[title]': {
                        required: "Title is required"
                    },
                    'ticket[description]': {
                        required: "Description is required"
                    }
                }
            });
        } );
    </script>
<% end %>

app/views/tickets/index.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      My Dashboard
    </h1>
  </div>
</div>
<!-- /.row -->

<% if notice %>
    <div class="alert alert-success">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>

<div class="row">
  <br>
  <div class="col-lg-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"> My all support tickets</h3>
      </div>
      <div class="panel-body">
        <table id="tickets" class="display" cellspacing="0" width="100%">
          <thead>
          <tr>
            <th>SL</th>
            <th>Ticket Title</th>
            <th>Ticket Description</th>
            <th>Status</th>
            <th>Created Date</th>
            <th>Edit</th>
            <th>Details</th>
          </tr>
          </thead>
          <tbody>
          <% sl = 1 %>
          <% @tickets.each do |ticket| %>
              <tr>
                <td><%= sl %></td>
                <td><%= ticket.title %></td>
                <td><%= ticket.description.truncate_words(5) %></td>
                <td><%= ticket.status %></td>
                <td><%= ticket.created_at.strftime("%m-%d-%Y") %></td>
                <td><a href="/customers/tickets/<%= ticket.id %>/edit">Edit</a></td>
                <td><a href="/customers/tickets/<%= ticket.id %>">Details</a></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<% content_for :special_script do %>
    <script>
        $(document).ready(function() {
            $('#tickets').DataTable();
        } );
    </script>
<% end %>

app/views/tickets/new.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      My Dashboard
    </h1>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"> Add a support ticket</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', ticket: @ticket, action: 'create' %>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<% content_for :special_script do %>
    <script>
        $(document).ready(function() {
            $("#validation").validate({
                rules: {
                    'ticket[title]': {
                        required: true
                    },
                    'ticket[description]': {
                        required: true
                    }
                },
                messages: {
                    'ticket[title]': {
                        required: "Title is required"
                    },
                    'ticket[description]': {
                        required: "Description is required"
                    }
                }
            });
        } );
    </script>
<% end %>

app/views/tickets/show.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      My Dashboard
    </h1>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <% if notice %>
        <div class="alert alert-success">
          <p id="notice"><%= notice %></p>
        </div>
    <% end %>
    <div class="panel panel-<% color = (@ticket.status == 'open')? 'green' : 'red' %><%= color %>">
      <div class="panel-heading">
        <h3 class="panel-title"> Ticket Status : <%= @ticket.status %></h3>
      </div>
      <div class="panel-body">
        <% if @ticket.status == 'open' %>
            <div class="col-md-12">
              <form action="/customers/tickets/<%= @ticket.id %>" method="post">
                <input name="utf8" type="hidden" value="&#x2713;">
                <input type="hidden" name="_method" value="patch">
                <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                <input type="hidden" name="ticket[status]" value="closed">
                <button type="submit" class="btn btn-warning pull-right">Close this ticket</button>
              </form>
            </div>
        <% end %>
        <h4><%= @ticket.title %></h4>
        <div class="well">
          <p><%= @ticket.description %></p>
        </div>
        <% @ticket.ticket_loops.each do |loop|  %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <% if loop.role == 'customer' %>
                    Reply of Me
                  <% else %>
                      Reply From : <%= User.find(@ticket.agent_id).name %>
                  <% end %>
                </h3>
              </div>
              <div class="panel-body">
                <%= loop.description %>
              </div>
            </div>
        <% end %>
        <% if @ticket.ticket_loops.size > 0 %>
            <hr>
            <%= render 'reply', ticket_loop: @ticket_loop, ticket_id:@ticket.id %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<% content_for :special_script do %>
    <script>
        $(document).ready(function() {
            $("#validation").validate({
                rules: {
                    'ticket_loop[description]': {
                        required: true
                    }
                },
                messages: {
                    'ticket_loop[description]': {
                        required: "Description is required"
                    }
                }
            });
        } );
    </script>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Role is : <%= @role %></h1>